language: objective-c
osx_image: xcode7.2
branches:
  only:
    - master
env:
  matrix:
    - DESTINATION="OS=9.2,name=iPhone 6"
before_install:
  - gem install xcpretty
script:
  - xcodebuild -version
  - xcodebuild -project CountdownLabel.xcodeproj -scheme CountdownLabelTests -sdk iphonesimulator -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test | xcpretty -c 
after_success:
  - bash <(curl -s https://codecov.io/bash)
